blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name='заголовок')
    slug = models.CharField(max_length=300, verbose_name='slug')
    content = models.TextField(verbose_name='содержание')
    preview_image = models.ImageField(null=True, blank=True,
                                      verbose_name='изображение для предпросмотра')
    created_at = models.DateTimeField(verbose_name='Дата создания статьи',
                                      auto_now_add=True, editable=False)
    is_published = models.BooleanField(default=False,
                                       verbose_name='опубликовано',
                                       help_text='Опубликовано')
    view_counter = models.PositiveIntegerField(default=0, editable=False,
                                               verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from blog.services import send_email


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview_image')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save(commit=False)
            blog.slug = slugify(blog.title)
            blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset().filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.is_published:
            self.object.view_counter += 1
            if self.object.view_counter == 100:
                send_email(self.object)
            self.object.save()
            return self.object
        else:
            return None


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview_image')

    def get_success_url(self):
        return reverse('blog:blog_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save(commit=False)
            blog.slug = slugify(blog.title)
            blog.save()
        return super().form_valid(form)


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить статью - {{ object.title }}?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-4 box-shadow">
    {% if blog %}
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{blog.title}}</h4>
    </div>
    <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{blog.content}}</li>
        </ul>

        <a class="btn btn-lg btn-block btn-warning" href="{% url 'blog:blog_update' object.pk %}">Изменить</a>


        <a class="btn btn-lg btn-block btn-danger" href="{% url 'blog:blog_delete' object.pk %}">Удалить</a>

        <div class="card-footer">Просмотров статьи: {{blog.view_counter}}</div>
    </div>
    {% else %}
    <h4 class="card-body">Данная статья не найдена</h4>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% if not object %}
                    <h1>Создать статью</h1>
                    {% else %}
                    <h1>Редактировать статью</h1>
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if not object %}
                        <button type="submit">Создать</button>
                        {% else %}
                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load media_tag %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_create' %}">Написать статью в блог</a>
</div>
    </div>
    </div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант размещения ваших продуктов
        для продажи</p>
</div>

<div class="container">

    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ blog.preview_image | media_tag }}"
                     width="300" height="300">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {{blog.title}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{blog.content | truncatechars:100 }}</li>
                    </ul>
                    <a class="btn btn-mb btn-outline-primary" href="{% url 'blog:blog_detail' blog.pk %}">Читать далее</a>

                    <a class="btn btn-mb btn-outline-primary" href="{% url 'blog:blog_update' blog.pk %}">Редактировать</a>

                    <a class="btn btn-mb btn-outline-primary" href="{% url 'blog:blog_delete' blog.pk %}">Удалить статью</a>

                </div>
            </div>
        </div>

        {% endfor %}

{% endblock %}