blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (UserCreateView, email_confirm_view, UserUpdateView,
                         UserDetailView, PasswordRecoveryView, CustomLoginView)

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('password-recovery/', PasswordRecoveryView.as_view(), name='password-recovery'),
    path('email-confirm/<str:token>/', email_confirm_view, name='email-confirm'),
    path('user-update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(
        unique=True, verbose_name='Email', help_text='Введите email'
    )
    phone_number = models.CharField(
        max_length=50, blank=True, null=True, verbose_name='Телефон',
        help_text='Введите номер телефона'
    )
    avatar = models.ImageField(
        upload_to='avatars/', blank=True, null=True, verbose_name='Аватар',
        help_text='Загрузите аватар'
    )
    token = models.CharField(max_length=100, blank=True, null=True, verbose_name='Токен')

    country = models.CharField(
        max_length=50, blank=True, null=True, verbose_name='Страна',
        help_text='Введите страну'
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['-date_joined']

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import Form, EmailField, EmailInput, ModelForm
from catalog.forms import StyleFormMixin
from users.models import User


class LoginForm(Form):
    email = forms.EmailField(
        max_length=150,
        label='Имя пользователя',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите email'
        })
    )
    password = forms.CharField(
        max_length=128,
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })
    )

    class Meta:
        model = User
        fields = ['email', 'password']


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class UserUpdateForm(StyleFormMixin, ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'phone_number', 'avatar', 'country']


class PasswordRecoveryForm(Form):
    email = EmailField(
        required=True,
        widget=EmailInput(
            attrs={
                'placeholder': 'Введите адрес электронной почты',
                'class': 'form-control text-center',
            }
        ),
    )

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView, FormView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserUpdateForm, PasswordRecoveryForm, \
    LoginForm
from users.models import User


class CustomLoginView(LoginView):
    authentication_form = LoginForm
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('blog:index')


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Confirm your email',
            message=f'Please click on the link to confirm your email: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    form_class = UserUpdateForm


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm

    def get_success_url(self):
        return reverse('users:profile',
                       kwargs={'pk': self.request.user.pk})


def email_confirm_view(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.token = None
    user.save()
    return redirect(reverse('users:login'))


class PasswordRecoveryView(FormView):
    model = User
    form_class = PasswordRecoveryForm
    template_name = 'users/password_recovery.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
            except ObjectDoesNotExist:
                form.add_error('email', 'Пользователь не найден')
                return self.form_invalid(form)
            password = User.objects.make_random_password(length=12)
            user.set_password(password)
            user.save()
            send_mail(
                subject='Your new password',
                message=f'Your new password is: {password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
            return super().form_valid(form)

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h1>Вход на сайт</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Войти</button>
                        <a class="btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
                        <a class="btn btn-outline-primary" href="{% url 'users:password-recovery' %}">Забыли пароль</a>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_recovery.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h1>Восстановление пароля</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary mt-3">Восстановить пароль</button>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h1>Регистрация</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Подтвердить</button>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'base.html' %}
{% load media_tag %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-outline-primary btb-right" href="{% url 'users:user-update' user.pk %}">Редактировать профиль</a>
</div>
    </div>
    </div>
<div class="col-6 card mb-4 box-shadow">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{user.first_name}} {{user.last_name}}</h4>
    </div>
    <div class="card-body">
        <img class="card-img-top img-fluid" src="{{ user.avatar | media_tag }}">
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{user.email}}</li>
            {% if user.phone_number %}
            <li>{{ user.phone_number }}</li>
            {% else %}
            <li>Вы еще не указали номер телефона</li>
            {% endif %}
            {% if user.country %}
            <li>{{user.country}}</li>
            {% else %}
            <li>Вы еще не указали страну</li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h1>Профиль</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить изменения</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}