blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ContactsTemplateView, ProductDetailView, ProductCreateView, \
    ProductDeleteView, ProductUpdateView, PersonalProductListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('personal_product_list/', PersonalProductListView.as_view(), name='personal_product_list'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование категории",
        help_text="Введите название категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта",
        help_text="Введите название продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта", help_text="Введите описание продукта"
    )
    image = models.ImageField(
        upload_to="products/photo",
        blank=True,
        null=True,
        verbose_name="Изображение продукта",
        help_text="Загрузите изображение продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория продукта",
        help_text="Введите название категории продукта",
        blank=True,
        null=True,
        related_name="products",
    )
    price = models.PositiveIntegerField(
        verbose_name="Цена за покупку", help_text="Введите цену за покупку"
    )
    created_at = models.DateTimeField(
        verbose_name="Дата создания",
        auto_now_add=True,
        help_text="Укажите дату создания",
    )
    updated_at = models.DateTimeField(
        verbose_name="Дата последнего изменения",
        auto_now=True,
        help_text="Укажите дату последнего изменения",
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE,
                              verbose_name='Автор', blank=True, null=True,
                              related_name='products')
    is_published = models.BooleanField(default=False,
                                       verbose_name='Доступно публике')

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["category", "name"]
        permissions = [
            ('product_set_published_status', 'Публиковать товар'),
            ('product_change_description', 'Изменять описание товара'),
            ('product_change_category', 'Изменять категорию товара'),
        ]

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='versions', verbose_name='продукт')
    version_number = models.CharField(max_length=100,
                                      verbose_name='номер версии')
    version_name = models.CharField(max_length=100,
                                    verbose_name='название версии')
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.version_name} - {self.version_number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django.forms import ModelForm, BooleanField, forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        product_name = self.cleaned_data['name']
        forbidden_words = ["казино", "криптовалюта", "крипта", "биржа",
                           "дешево", "бесплатно", "обман", "полиция", "радар"]
        for word in forbidden_words:
            if word in product_name.lower():
                raise forms.ValidationError(
                    "Введенное название содержит запрещенные слова")
        return product_name

    def clean_description(self):
        description = self.cleaned_data['description']
        forbidden_words = ["казино", "криптовалюта", "крипта", "биржа",
                           "дешево", "бесплатно", "обман", "полиция", "радар"]
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError(
                    "Введенное описание содержит запрещенные слова")
        return description


class ProductModerationForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('is_published', 'description', 'category',)


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, TemplateView, DetailView, DeleteView, CreateView, UpdateView

from catalog.forms import ProductForm, VersionForm, ProductModerationForm
from catalog.models import Product, Version


class ContactsTemplateView(TemplateView):
    template_name = 'contacts.html'


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser or self.request.user.has_perm('catalog.view_product'):
            return Product.objects.all()
        return Product.objects.filter(is_published=True).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for obj in context['object_list']:
            obj.active_version = obj.versions.filter(
                is_active=True).first() if obj.versions.filter(
                is_active=True).first() else "Активная версия не найдена"
        return context


class PersonalProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser or self.request.user.has_perm('catalog.view_product'):
            return Product.objects.all()
        return Product.objects.filter(owner=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for obj in context['object_list']:
            obj.active_version = obj.versions.filter(
                is_active=True).first() if obj.versions.filter(
                is_active=True).first() else "Активная версия не найдена"
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_list')

    def form_valid(self, form):
        product = form.save(commit=False)
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if type(context['form']) == ProductForm:
            ProductFormset = inlineformset_factory(Product, Version, VersionForm,
                                                   extra=1)
            if self.request.method == 'POST':
                context['formset'] = ProductFormset(self.request.POST,
                                                    instance=self.object)
            else:
                context['formset'] = ProductFormset(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context.get('formset')
        if formset:
            if form.is_valid() and formset.is_valid():
                active_version = 0
                for i in formset.forms:
                    if i.cleaned_data.get('is_active'):
                        active_version += 1
                    if active_version > 1:
                        form.add_error(None,
                                       'Вы можете выбрать только одну активную версию')
                        return self.form_invalid(form)
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        elif form.is_valid():
            form.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(
                self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return ProductForm
        if user.has_perms(
                ['catalog.product_set_published_status', 'catalog.product_change_description',
                 'catalog.product_change_category']):
            return ProductModerationForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product

    def get_success_url(self, *args, **kwargs):
        return reverse('catalog:product_list')

catalog/templates/catalog/product_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт - {{ object.name}}?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}
{% load media_tag %}
{% block content %}
<div class="card mb-4 box-shadow">
    <img class="card-img-top"
                     src="{{ product.image | media_tag }}"
                     width="300" height="300">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{product.name}}</h4>
    </div>
    <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{product.description}}</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">
            {{product.price}} руб.
        </button>
        {% if perms.catalog.product_set_published_status and perms.catalog.product_change_description and perms.catalog.product_change_category or user == product.owner or user.is_superuser %}
        <a class="btn btn-lg btn-block btn-warning" href="{% url 'catalog:product_update' object.pk %}">Изменить</a>
        {% endif %}
        {% if user == product.owner or user.is_superuser %}
        <a class="btn btn-lg btn-block btn-danger" href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {% if object %}
                        <h3>Изменить описание продукта</h3>
                        {% else %}
                        <h3>Добавить продукт</h3>
                        {% endif %}
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        {% else %}
                        <button type="submit" class="btn btn-success">Добавить</button>
                        {% endif %}
                        {% if object %}
                        <a class="btn btn-primary "
                           href="{% url 'catalog:product_detail' object.pk %}">Отмена</a>
                        {% else %}
                        <a class="btn btn-primary "
                           href="{% url 'catalog:product_list' %}">Отмена</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if formset %}
            <div class="col-6">
                <div class="card-header"> Управление версиями продукта</div>
                {{ formset.management_form }}
                {% for form in formset %}
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load media_tag %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-outline-primary btb-right" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
</div>
    </div>
    </div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант размещения ваших продуктов
        для продажи</p>
</div>

<div class="container">

    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ product.image | media_tag }}"
                     width="300" height="300">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {{product.name}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{product.description | truncatechars:100}}</li>
                    </ul>
                    <a class="btn btn-mb btn-outline-primary"
                       href="{% url 'catalog:product_detail' product.pk %}">Подробности</a>
                    <hr>
                    <div class="card-footer text-muted mt-2">
                        {{ product.active_version }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}